import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import fs from "fs/promises";

import Header from "../components/header";
import Link from "next/link";

export default function Home({ latestComics: latestComicsString }) {
  const latestComics = latestComicsString.map((comic) => {
    let json = JSON.parse(comic);
    return json;
  });
  console.log(latestComics);
  return (
    <div className="h-screen bg-black text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="grid place-content-center">
        <section className="grid grid-cols-1 gap-2 max-w-md sm:grid-cols-2 md:grid-cols-3">
          {latestComics.map(({ id, title, alt, img, height, width }) => {
            return (
              <Link href={`/comic/${id}`} key={id}>
                <a className="mb-4 pb-4 m-auto">
                  <h3 className="font-bold text-sm text-center pb-2">
                    {title}
                  </h3>
                  <Image
                    className="aspect-square"
                    alt={alt}
                    src={img}
                    height={height}
                    width={width}
                  />{" "}
                </a>
              </Link>
            );
          })}
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const files = await fs.readdir("./comics");
  const latestComicsFiles = files.slice(-8, -1);

  const promisesReadFiles = latestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, "utf8");
    return content;
  });

  const latestComics = await Promise.all(promisesReadFiles);
  return {
    props: {
      latestComics,
    },
  };
}
